sudo: required
services:
  - docker

before_install:
  - docker build -t ahmad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ahmad/docker-react npm run test -- --coverage

# Deploy:
#    provider: elasticbreanstalk
#    region:
#    app:
#    env:
#    bucket_name:
#    bucket_path:
#    on:
#      branch: master